-- 作成したDBに接続
\c main_db;

-- ドキュメントテーブル作成
DROP TABLE IF EXISTS documents;
CREATE TABLE documents (
	document_id SERIAL PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	content TEXT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--オブジェクトの名前とファイル名を保存するテーブル
DROP TABLE IF EXISTS object;
CREATE TABLE object (
	object_id SERIAL PRIMARY KEY,
	object_name VARCHAR(100) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);